//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syn.VA.Libraries.Language.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syn.VA.Libraries.Language.Locale.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Avatar.
        /// </summary>
        public static string AvatarPlugin_AvatarLabelContent {
            get {
                return ResourceManager.GetString("AvatarPlugin_AvatarLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Background.
        /// </summary>
        public static string AvatarPlugin_BackgroundLabelContent {
            get {
                return ResourceManager.GetString("AvatarPlugin_BackgroundLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Background Color.
        /// </summary>
        public static string AvatarPlugin_ColorToggleContent {
            get {
                return ResourceManager.GetString("AvatarPlugin_ColorToggleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Avatar.
        /// </summary>
        public static string AvatarPlugin_DisplayName {
            get {
                return ResourceManager.GetString("AvatarPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender of this Avatar does not match the Gender set for Speech Synthesis..
        /// </summary>
        public static string AvatarPlugin_GenderMismatchMessage {
            get {
                return ResourceManager.GetString("AvatarPlugin_GenderMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string BrowserWindowTitle {
            get {
                return ResourceManager.GetString("BrowserWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API.
        /// </summary>
        public static string ChannelPlugin_DisplayName {
            get {
                return ResourceManager.GetString("ChannelPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Message(s).
        /// </summary>
        public static string ChannelPlugin_MessageReceivedLabel {
            get {
                return ResourceManager.GetString("ChannelPlugin_MessageReceivedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API Interface settings saved..
        /// </summary>
        public static string ChannelPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("ChannelPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API is Disabled.
        /// </summary>
        public static string ChannelPlugin_ToggleOffLabel {
            get {
                return ResourceManager.GetString("ChannelPlugin_ToggleOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web API is Enabled.
        /// </summary>
        public static string ChannelPlugin_ToggleOnLabel {
            get {
                return ResourceManager.GetString("ChannelPlugin_ToggleOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command for Closing Window.
        /// </summary>
        public static string CommandCloseToggleSwitchContent {
            get {
                return ResourceManager.GetString("CommandCloseToggleSwitchContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel &amp; External Directories.
        /// </summary>
        public static string CommonPlugin_DisplayName {
            get {
                return ResourceManager.GetString("CommonPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can I say?.
        /// </summary>
        public static string DefaultHint {
            get {
                return ResourceManager.GetString("DefaultHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary &amp; Thesaraus.
        /// </summary>
        public static string DictionaryPlugin_DisplayName {
            get {
                return ResourceManager.GetString("DictionaryPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common definitions only.
        /// </summary>
        public static string DictionaryPlugin_ToggleButtonContent {
            get {
                return ResourceManager.GetString("DictionaryPlugin_ToggleButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string DisplayPlugin_DisplayName {
            get {
                return ResourceManager.GetString("DisplayPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Modes.
        /// </summary>
        public static string DisplayPlugin_ModeLabelContent {
            get {
                return ResourceManager.GetString("DisplayPlugin_ModeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Restart.
        /// </summary>
        public static string DisplayPlugin_RestartButtonContent {
            get {
                return ResourceManager.GetString("DisplayPlugin_RestartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: example@Gmail.com.
        /// </summary>
        public static string EmailPlugin_BotEmailWatermark {
            get {
                return ResourceManager.GetString("EmailPlugin_BotEmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Configuration.
        /// </summary>
        public static string EmailPlugin_DisplayName {
            get {
                return ResourceManager.GetString("EmailPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Email ID.
        /// </summary>
        public static string EmailPlugin_EmailLabelContent {
            get {
                return ResourceManager.GetString("EmailPlugin_EmailLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new emails every 5 Minutes.
        /// </summary>
        public static string EmailPlugin_ServiceDescription {
            get {
                return ResourceManager.GetString("EmailPlugin_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email configuration updated..
        /// </summary>
        public static string EmailPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("EmailPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email Service Provider.
        /// </summary>
        public static string EmailPlugin_UserEmailLabelContent {
            get {
                return ResourceManager.GetString("EmailPlugin_UserEmailLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Outlook.com.
        /// </summary>
        public static string EmailPlugin_UserEmailWatermark {
            get {
                return ResourceManager.GetString("EmailPlugin_UserEmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords Do Not Match!.
        /// </summary>
        public static string EmailPlugin_WrongPasswordMessage {
            get {
                return ResourceManager.GetString("EmailPlugin_WrongPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horoscope.
        /// </summary>
        public static string HoroscopePlugin_DisplayName {
            get {
                return ResourceManager.GetString("HoroscopePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Zodiac Sign.
        /// </summary>
        public static string HoroscopePlugin_SelectionLabelContent {
            get {
                return ResourceManager.GetString("HoroscopePlugin_SelectionLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string InteractionPlugin_DisplayName {
            get {
                return ResourceManager.GetString("InteractionPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise intelligent events based on user interaction.
        /// </summary>
        public static string InteractionPlugin_ServiceDescription {
            get {
                return ResourceManager.GetString("InteractionPlugin_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a name for this file.
        /// </summary>
        public static string LauncherPlugin_AddFileMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string LauncherPlugin_AddFileTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a name for this folder.
        /// </summary>
        public static string LauncherPlugin_AddFolderMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        public static string LauncherPlugin_AddFolderTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the URL of the search engine. Use {0} for query replacement..
        /// </summary>
        public static string LauncherPlugin_AddSearchEngineAddressMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddSearchEngineAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Address.
        /// </summary>
        public static string LauncherPlugin_AddSearchEngineAddressTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddSearchEngineAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type a name for the search engine. Example &apos;Google&apos;.
        /// </summary>
        public static string LauncherPlugin_AddSearchEngineNameMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddSearchEngineNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Name.
        /// </summary>
        public static string LauncherPlugin_AddSearchEngineNameTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddSearchEngineNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the URL of the website..
        /// </summary>
        public static string LauncherPlugin_AddWebsiteAddressMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddWebsiteAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Address.
        /// </summary>
        public static string LauncherPlugin_AddWebsiteAddressTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddWebsiteAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type a name for the website. Example &apos;Google&apos;.
        /// </summary>
        public static string LauncherPlugin_AddWebsiteNameMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddWebsiteNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Name.
        /// </summary>
        public static string LauncherPlugin_AddWebsiteNameTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddWebsiteNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files, Folders &amp; Websites.
        /// </summary>
        public static string LauncherPlugin_DisplayName {
            get {
                return ResourceManager.GetString("LauncherPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Licenses.
        /// </summary>
        public static string LicensePlugin_AdditionalLicenseButtonContent {
            get {
                return ResourceManager.GetString("LicensePlugin_AdditionalLicenseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture:.
        /// </summary>
        public static string LicensePlugin_ArchitectureLabelContent {
            get {
                return ResourceManager.GetString("LicensePlugin_ArchitectureLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version:.
        /// </summary>
        public static string LicensePlugin_CurrentVersionLabelContent {
            get {
                return ResourceManager.GetString("LicensePlugin_CurrentVersionLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicensePlugin_DisplayName {
            get {
                return ResourceManager.GetString("LicensePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework:.
        /// </summary>
        public static string LicensePlugin_FrameworkLabelContent {
            get {
                return ResourceManager.GetString("LicensePlugin_FrameworkLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Full License [Online].
        /// </summary>
        public static string LicensePlugin_LicenseButtonContent {
            get {
                return ResourceManager.GetString("LicensePlugin_LicenseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed Version:.
        /// </summary>
        public static string LicensePlugin_LicensedVersionLabelContent {
            get {
                return ResourceManager.GetString("LicensePlugin_LicensedVersionLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensee:.
        /// </summary>
        public static string LicensePlugin_LicenseeLabelContent {
            get {
                return ResourceManager.GetString("LicensePlugin_LicenseeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type:.
        /// </summary>
        public static string LicensePlugin_LicenseTypeLabelContent {
            get {
                return ResourceManager.GetString("LicensePlugin_LicenseTypeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensor:.
        /// </summary>
        public static string LicensePlugin_LicensorLabelContent {
            get {
                return ResourceManager.GetString("LicensePlugin_LicensorLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial License Key:.
        /// </summary>
        public static string LicensePlugin_PartialKeyLabelContent {
            get {
                return ResourceManager.GetString("LicensePlugin_PartialKeyLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Privacy Policy [Online].
        /// </summary>
        public static string LicensePlugin_PrivacyButtonContent {
            get {
                return ResourceManager.GetString("LicensePlugin_PrivacyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Zoom.
        /// </summary>
        public static string MapPlugin_DefaultZoomLabelContent {
            get {
                return ResourceManager.GetString("MapPlugin_DefaultZoomLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string MapPlugin_DisplayName {
            get {
                return ResourceManager.GetString("MapPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Provider.
        /// </summary>
        public static string MapPlugin_MapProviderLabelContent {
            get {
                return ResourceManager.GetString("MapPlugin_MapProviderLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Zoom.
        /// </summary>
        public static string MapPlugin_MaximumZoomLabelContent {
            get {
                return ResourceManager.GetString("MapPlugin_MaximumZoomLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Zoom.
        /// </summary>
        public static string MapPlugin_MinimumZoomLabelContent {
            get {
                return ResourceManager.GetString("MapPlugin_MinimumZoomLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map settings have been saved..
        /// </summary>
        public static string MapPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("MapPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs &amp; Videos.
        /// </summary>
        public static string MediaPlugin_DisplayName {
            get {
                return ResourceManager.GetString("MediaPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing has started. You will be notified when indexing is over..
        /// </summary>
        public static string MediaPlugin_IndexingMessage {
            get {
                return ResourceManager.GetString("MediaPlugin_IndexingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Songs Directory (Indexed {0} Files).
        /// </summary>
        public static string MediaPlugin_MusicDirectoryLabelContentFormat {
            get {
                return ResourceManager.GetString("MediaPlugin_MusicDirectoryLabelContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Videos Directory (Indexed {0} Files).
        /// </summary>
        public static string MediaPlugin_VideoDirectoryLabelContentFormat {
            get {
                return ResourceManager.GetString("MediaPlugin_VideoDirectoryLabelContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Bot API key removed..
        /// </summary>
        public static string MessagingPlugin_ApiClearedMessage {
            get {
                return ResourceManager.GetString("MessagingPlugin_ApiClearedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Bot API Key.
        /// </summary>
        public static string MessagingPlugin_ApiKeyLabelContent {
            get {
                return ResourceManager.GetString("MessagingPlugin_ApiKeyLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Connect Disabled.
        /// </summary>
        public static string MessagingPlugin_AutoConnectOffLabelContent {
            get {
                return ResourceManager.GetString("MessagingPlugin_AutoConnectOffLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Connect Enabled.
        /// </summary>
        public static string MessagingPlugin_AutoConnectOnLabelContent {
            get {
                return ResourceManager.GetString("MessagingPlugin_AutoConnectOnLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Bot.
        /// </summary>
        public static string MessagingPlugin_DisplayName {
            get {
                return ResourceManager.GetString("MessagingPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Bot API saved..
        /// </summary>
        public static string MessagingPlugin_SettingsSaved {
            get {
                return ResourceManager.GetString("MessagingPlugin_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What shall I call you?.
        /// </summary>
        public static string NameMessageText {
            get {
                return ResourceManager.GetString("NameMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Developer!.
        /// </summary>
        public static string NameMessageTitle {
            get {
                return ResourceManager.GetString("NameMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you {0}! Would you like to run the Speech Recognition Test?.
        /// </summary>
        public static string NameSpecifiedMessage {
            get {
                return ResourceManager.GetString("NameSpecifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to run the Speech Recognition Test?.
        /// </summary>
        public static string NameUnspecifiedMessage {
            get {
                return ResourceManager.GetString("NameUnspecifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Monitor.
        /// </summary>
        public static string PerfPlugin_DisplayName {
            get {
                return ResourceManager.GetString("PerfPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush Now.
        /// </summary>
        public static string PerfPlugin_FlushButtonContent {
            get {
                return ResourceManager.GetString("PerfPlugin_FlushButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Flushing Interval.
        /// </summary>
        public static string PerfPlugin_FlushLabelContent {
            get {
                return ResourceManager.GetString("PerfPlugin_FlushLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Memory Flushing Off.
        /// </summary>
        public static string PerfPlugin_FlushSwitchOffLabel {
            get {
                return ResourceManager.GetString("PerfPlugin_FlushSwitchOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Memory Flushing On.
        /// </summary>
        public static string PerfPlugin_FlushSwitchOnLabel {
            get {
                return ResourceManager.GetString("PerfPlugin_FlushSwitchOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Monitored CPU Usage: {0}.
        /// </summary>
        public static string PerfPlugin_LastCpuUsage {
            get {
                return ResourceManager.GetString("PerfPlugin_LastCpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Monitored Disk Usage: {0}.
        /// </summary>
        public static string PerfPlugin_LastDiskUsage {
            get {
                return ResourceManager.GetString("PerfPlugin_LastDiskUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Monitored GC Allocation: {0}.
        /// </summary>
        public static string PerfPlugin_LastGc {
            get {
                return ResourceManager.GetString("PerfPlugin_LastGc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Recorded Memory Flush: {0}.
        /// </summary>
        public static string PerfPlugin_LastMemoryFlush {
            get {
                return ResourceManager.GetString("PerfPlugin_LastMemoryFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Monitored RAM Usage: {0}.
        /// </summary>
        public static string PerfPlugin_LastRamUsage {
            get {
                return ResourceManager.GetString("PerfPlugin_LastRamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minute(s).
        /// </summary>
        public static string PerfPlugin_Minute {
            get {
                return ResourceManager.GetString("PerfPlugin_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that the Microphone is properly connected and then press the OK button..
        /// </summary>
        public static string ReadyMessageText {
            get {
                return ResourceManager.GetString("ReadyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Ready.
        /// </summary>
        public static string ReadyMessageTitle {
            get {
                return ResourceManager.GetString("ReadyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        public static string ReminderPlugin_DisplayName {
            get {
                return ResourceManager.GetString("ReminderPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Reminder Service.
        /// </summary>
        public static string ReminderPlugin_ReminderServiceDescription {
            get {
                return ResourceManager.GetString("ReminderPlugin_ReminderServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        public static string ReminderPlugin_TabItemHeader {
            get {
                return ResourceManager.GetString("ReminderPlugin_TabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset and Shutdown.
        /// </summary>
        public static string ResetAndShutdown {
            get {
                return ResourceManager.GetString("ResetAndShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string ResourceDropDownButtonText {
            get {
                return ResourceManager.GetString("ResourceDropDownButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engines.
        /// </summary>
        public static string SearchEngines {
            get {
                return ResourceManager.GetString("SearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services &amp; Plugins.
        /// </summary>
        public static string ServicePlugin_DisplayName {
            get {
                return ResourceManager.GetString("ServicePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify if a Drive is low on space.
        /// </summary>
        public static string ServicePlugin_DriveSpaceReminderServiceDescription {
            get {
                return ResourceManager.GetString("ServicePlugin_DriveSpaceReminderServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind System uptime every 1 hour.
        /// </summary>
        public static string ServicePlugin_SystemUptimeReminderServiceDescription {
            get {
                return ResourceManager.GetString("ServicePlugin_SystemUptimeReminderServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind the time every 1 hour..
        /// </summary>
        public static string ServicePlugin_TimeReminderServiceDescription {
            get {
                return ResourceManager.GetString("ServicePlugin_TimeReminderServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Panel Password.
        /// </summary>
        public static string SettingPanel_PasswordWatermark {
            get {
                return ResourceManager.GetString("SettingPanel_PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Settings Panel password to continue..
        /// </summary>
        public static string SettingsPanel_PasswordDialogText {
            get {
                return ResourceManager.GetString("SettingsPanel_PasswordDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Protected.
        /// </summary>
        public static string SettingsPanel_PasswordDialogTitle {
            get {
                return ResourceManager.GetString("SettingsPanel_PasswordDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Panel.
        /// </summary>
        public static string SettingsPanel_Title {
            get {
                return ResourceManager.GetString("SettingsPanel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the ID of the Skype user..
        /// </summary>
        public static string SkypePlugin_AddIdDescription {
            get {
                return ResourceManager.GetString("SkypePlugin_AddIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype User ID.
        /// </summary>
        public static string SkypePlugin_AddIdTitle {
            get {
                return ResourceManager.GetString("SkypePlugin_AddIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a name for this Skype user..
        /// </summary>
        public static string SkypePlugin_AddNameDescription {
            get {
                return ResourceManager.GetString("SkypePlugin_AddNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype User Name.
        /// </summary>
        public static string SkypePlugin_AddNameTitle {
            get {
                return ResourceManager.GetString("SkypePlugin_AddNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string SkypePlugin_DisplayName {
            get {
                return ResourceManager.GetString("SkypePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Skype Contact(s).
        /// </summary>
        public static string SkypePlugin_KnownUserLabelContent {
            get {
                return ResourceManager.GetString("SkypePlugin_KnownUserLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Skype Call.
        /// </summary>
        public static string SkypePlugin_TestButtonContent {
            get {
                return ResourceManager.GetString("SkypePlugin_TestButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype User Added..
        /// </summary>
        public static string SkypePlugin_UserAdded {
            get {
                return ResourceManager.GetString("SkypePlugin_UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype User Removed..
        /// </summary>
        public static string SkypePlugin_UserRemoved {
            get {
                return ResourceManager.GetString("SkypePlugin_UserRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phrase you wish to save as a choice.
        /// </summary>
        public static string SpeechPlugin_AddChoiceDialogMessage {
            get {
                return ResourceManager.GetString("SpeechPlugin_AddChoiceDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Choice.
        /// </summary>
        public static string SpeechPlugin_AddChoiceDialogTitle {
            get {
                return ResourceManager.GetString("SpeechPlugin_AddChoiceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Choice List.
        /// </summary>
        public static string SpeechPlugin_ChoicesWindowTitle {
            get {
                return ResourceManager.GetString("SpeechPlugin_ChoicesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Speech Choices.
        /// </summary>
        public static string SpeechPlugin_ChoiceTabItemHeader {
            get {
                return ResourceManager.GetString("SpeechPlugin_ChoiceTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition &amp; Synthesis.
        /// </summary>
        public static string SpeechPlugin_DisplayName {
            get {
                return ResourceManager.GetString("SpeechPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Choice List.
        /// </summary>
        public static string SpeechPlugin_EditChoiceButtonContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_EditChoiceButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition Engine.
        /// </summary>
        public static string SpeechPlugin_EngineLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_EngineLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRGS.
        /// </summary>
        public static string SpeechPlugin_GrammarTabItemHeader {
            get {
                return ResourceManager.GetString("SpeechPlugin_GrammarTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Volume.
        /// </summary>
        public static string SpeechPlugin_MasterVolumeLabel {
            get {
                return ResourceManager.GetString("SpeechPlugin_MasterVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Volume.
        /// </summary>
        public static string SpeechPlugin_MicrophoneVolumeLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_MicrophoneVolumeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Rank (Equal and Above).
        /// </summary>
        public static string SpeechPlugin_RankLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_RankLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New speech settings saved..
        /// </summary>
        public static string SpeechPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("SpeechPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Speech Confidence.
        /// </summary>
        public static string SpeechPlugin_SynthesisConfidenceLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_SynthesisConfidenceLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Synthesis Rate.
        /// </summary>
        public static string SpeechPlugin_SynthesisRateLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_SynthesisRateLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Synthesis Engine.
        /// </summary>
        public static string SpeechPlugin_SynthesizerLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_SynthesizerLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesizer Voice.
        /// </summary>
        public static string SpeechPlugin_VoiceLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_VoiceLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Synthesis Volume.
        /// </summary>
        public static string SpeechPlugin_VolumeLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_VolumeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition.
        /// </summary>
        public static string SpeechRecognition {
            get {
                return ResourceManager.GetString("SpeechRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to hear &apos;{0}&apos;.
        /// </summary>
        public static string SpeechTestSnippetMessage {
            get {
                return ResourceManager.GetString("SpeechTestSnippetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please say &apos;{0}&apos;.
        /// </summary>
        public static string SpeechTestSnippetTitle {
            get {
                return ResourceManager.GetString("SpeechTestSnippetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Assistant.
        /// </summary>
        public static string SpeechTestText {
            get {
                return ResourceManager.GetString("SpeechTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need any help just say or type &apos;What can I say?&apos;.
        /// </summary>
        public static string StartMessageText {
            get {
                return ResourceManager.GetString("StartMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Start!.
        /// </summary>
        public static string StartMessageTitle {
            get {
                return ResourceManager.GetString("StartMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthetic Intelligence Network News Feed.
        /// </summary>
        public static string SynFeedServiceDescription {
            get {
                return ResourceManager.GetString("SynFeedServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition Test failed. You can anytime refer our Online Tutorials to calibrate Speech Recognition..
        /// </summary>
        public static string TestFailedMessageText {
            get {
                return ResourceManager.GetString("TestFailedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        public static string TestFailedMessageTitle {
            get {
                return ResourceManager.GetString("TestFailedMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition Test passed..
        /// </summary>
        public static string TestPassedMessageText {
            get {
                return ResourceManager.GetString("TestPassedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome!.
        /// </summary>
        public static string TestPassedMessageTitle {
            get {
                return ResourceManager.GetString("TestPassedMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Rock! Thank you for installing Syn Virtual Assistant!.
        /// </summary>
        public static string ThankMessage {
            get {
                return ResourceManager.GetString("ThankMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic Tac Toe.
        /// </summary>
        public static string TicTacToePlugin_DisplayName {
            get {
                return ResourceManager.GetString("TicTacToePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Difficulty.
        /// </summary>
        public static string TicTacToePlugin_PlayerDifficultyContent {
            get {
                return ResourceManager.GetString("TicTacToePlugin_PlayerDifficultyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Player.
        /// </summary>
        public static string TicTacToePlugin_PlayerLabelContent {
            get {
                return ResourceManager.GetString("TicTacToePlugin_PlayerLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        public static string TranslatorPlugin_DisplayName {
            get {
                return ResourceManager.GetString("TranslatorPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Source Language.
        /// </summary>
        public static string TranslatorPlugin_LanguageLabelContent {
            get {
                return ResourceManager.GetString("TranslatorPlugin_LanguageLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source language updated..
        /// </summary>
        public static string TranslatorPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("TranslatorPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update, version {version} is now available. Please visit {link} to download the latest version..
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserPlugin_DisplayName {
            get {
                return ResourceManager.GetString("UserPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (The Bot will call you by this name).
        /// </summary>
        public static string UserPlugin_NameLabelContent {
            get {
                return ResourceManager.GetString("UserPlugin_NameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information stored..
        /// </summary>
        public static string UserPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("UserPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Syn Directory.
        /// </summary>
        public static string VA_BrowseInstallationDirectory {
            get {
                return ResourceManager.GetString("VA_BrowseInstallationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Bot Knowledge-Base Directory.
        /// </summary>
        public static string VA_ExternalBotPathWatermark {
            get {
                return ResourceManager.GetString("VA_ExternalBotPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Plugins Directory.
        /// </summary>
        public static string VA_ExternalPluginsPathWatermark {
            get {
                return ResourceManager.GetString("VA_ExternalPluginsPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already running..
        /// </summary>
        public static string VA_MultipleInstanceMessageFormat {
            get {
                return ResourceManager.GetString("VA_MultipleInstanceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to Reset the Virtual Assistant?.
        /// </summary>
        public static string VA_ResetConfirmationMessage {
            get {
                return ResourceManager.GetString("VA_ResetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Confirmation.
        /// </summary>
        public static string VA_ResetConfirmationTitle {
            get {
                return ResourceManager.GetString("VA_ResetConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Virtual Assistant.
        /// </summary>
        public static string VA_RestartButtonContent {
            get {
                return ResourceManager.GetString("VA_RestartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string VA_UpdateMessageTitle {
            get {
                return ResourceManager.GetString("VA_UpdateMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string WeatherPlugin_DisplayName {
            get {
                return ResourceManager.GetString("WeatherPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Current Location.
        /// </summary>
        public static string WeatherPlugin_LocationLabelContent {
            get {
                return ResourceManager.GetString("WeatherPlugin_LocationLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Location.
        /// </summary>
        public static string WeatherPlugin_SaveButtonContent {
            get {
                return ResourceManager.GetString("WeatherPlugin_SaveButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location for weather report has now been saved..
        /// </summary>
        public static string WeatherPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("WeatherPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather report every 2 hours.
        /// </summary>
        public static string WeatherPlugin_WeatherReportServiceDescription {
            get {
                return ResourceManager.GetString("WeatherPlugin_WeatherReportServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Websites {
            get {
                return ResourceManager.GetString("Websites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Developer.
        /// </summary>
        public static string WelcomePlugin_DisplayName {
            get {
                return ResourceManager.GetString("WelcomePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string WindowsPlugin_DisplayName {
            get {
                return ResourceManager.GetString("WindowsPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Directory.
        /// </summary>
        public static string WindowsPlugin_ScreenshotLabelContent {
            get {
                return ResourceManager.GetString("WindowsPlugin_ScreenshotLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Directory.
        /// </summary>
        public static string WindowsPlugin_WallpaperLabelContent {
            get {
                return ResourceManager.GetString("WindowsPlugin_WallpaperLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfram Alpha Developer API Key.
        /// </summary>
        public static string WolframPlugin_ApiLabelContent {
            get {
                return ResourceManager.GetString("WolframPlugin_ApiLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfram Alpha.
        /// </summary>
        public static string WolframPlugin_DisplayName {
            get {
                return ResourceManager.GetString("WolframPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfram API Key has now been saved. You may now use the Wolfram Alpha features..
        /// </summary>
        public static string WolframPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("WolframPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
