//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syn.VA.Libraries.Language.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syn.VA.Libraries.Language.Locale.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Required.
        /// </summary>
        public static string Assistant_AuthenticationWindow_LabelContent {
            get {
                return ResourceManager.GetString("Assistant_AuthenticationWindow_LabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string Assistant_AuthenticationWindow_PasswordBoxWatermark {
            get {
                return ResourceManager.GetString("Assistant_AuthenticationWindow_PasswordBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Assistant_AuthenticationWindowTitle {
            get {
                return ResourceManager.GetString("Assistant_AuthenticationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Assistant_LicenseWindowTitle {
            get {
                return ResourceManager.GetString("Assistant_LicenseWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Assistant_LogWindowTitle {
            get {
                return ResourceManager.GetString("Assistant_LogWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin offers no editable settings..
        /// </summary>
        public static string Assistant_SettingsWindow_DefaultLabelContent {
            get {
                return ResourceManager.GetString("Assistant_SettingsWindow_DefaultLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string AvatarPlugin_DisplayName {
            get {
                return ResourceManager.GetString("AvatarPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Avatar (Please change the Speech settings accordingly).
        /// </summary>
        public static string AvatarPlugin_SelectAvatarLabelContent {
            get {
                return ResourceManager.GetString("AvatarPlugin_SelectAvatarLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Panel Mode.
        /// </summary>
        public static string BrandPlugin_AvatarModeLabelContent {
            get {
                return ResourceManager.GetString("BrandPlugin_AvatarModeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding.
        /// </summary>
        public static string BrandPlugin_DisplayName {
            get {
                return ResourceManager.GetString("BrandPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Placeholder.
        /// </summary>
        public static string BrandPlugin_InputPlaceholderLabelContent {
            get {
                return ResourceManager.GetString("BrandPlugin_InputPlaceholderLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro Title.
        /// </summary>
        public static string BrandPlugin_IntroTitleLabelContent {
            get {
                return ResourceManager.GetString("BrandPlugin_IntroTitleLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo file path.
        /// </summary>
        public static string BrandPlugin_LogoFilePathTextBoxWatermark {
            get {
                return ResourceManager.GetString("BrandPlugin_LogoFilePathTextBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string BrandPlugin_PanelConfirmPasswordLabelContent {
            get {
                return ResourceManager.GetString("BrandPlugin_PanelConfirmPasswordLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Panel Password (Empty for No Password).
        /// </summary>
        public static string BrandPlugin_PanelPasswordLabelContent {
            get {
                return ResourceManager.GetString("BrandPlugin_PanelPasswordLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match. Settings not saved..
        /// </summary>
        public static string BrandPlugin_PasswordMismatchMessage {
            get {
                return ResourceManager.GetString("BrandPlugin_PasswordMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Button Text.
        /// </summary>
        public static string BrandPlugin_RefreshTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("BrandPlugin_RefreshTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show Refresh Button.
        /// </summary>
        public static string BrandPlugin_RefreshToggleButtonOffContent {
            get {
                return ResourceManager.GetString("BrandPlugin_RefreshToggleButtonOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Refresh Button.
        /// </summary>
        public static string BrandPlugin_RefreshToggleButtonOnContent {
            get {
                return ResourceManager.GetString("BrandPlugin_RefreshToggleButtonOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not display logo.
        /// </summary>
        public static string BrandPlugin_UseLogoToggleButtonOffContent {
            get {
                return ResourceManager.GetString("BrandPlugin_UseLogoToggleButtonOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Logo.
        /// </summary>
        public static string BrandPlugin_UseLogoToggleButtonOnContent {
            get {
                return ResourceManager.GetString("BrandPlugin_UseLogoToggleButtonOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        public static string BrandPlugin_WindowTitleLabelContent {
            get {
                return ResourceManager.GetString("BrandPlugin_WindowTitleLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string BrowserPlugin_BrowserWindowTitleContent {
            get {
                return ResourceManager.GetString("BrowserPlugin_BrowserWindowTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string BrowserPlugin_DisplayName {
            get {
                return ResourceManager.GetString("BrowserPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Common_Applications {
            get {
                return ResourceManager.GetString("Common_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Common_Country {
            get {
                return ResourceManager.GetString("Common_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Common_Directories {
            get {
                return ResourceManager.GetString("Common_Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Common_FirstName {
            get {
                return ResourceManager.GetString("Common_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Common_Gender {
            get {
                return ResourceManager.GetString("Common_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Common_LastName {
            get {
                return ResourceManager.GetString("Common_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engines.
        /// </summary>
        public static string Common_SearchEngines {
            get {
                return ResourceManager.GetString("Common_SearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        public static string Common_Websites {
            get {
                return ResourceManager.GetString("Common_Websites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Discord Bot Token.
        /// </summary>
        public static string DiscordPlugin_BotTokenLabelContent {
            get {
                return ResourceManager.GetString("DiscordPlugin_BotTokenLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Bot is Off.
        /// </summary>
        public static string DiscordPlugin_ChannelToggleOffContent {
            get {
                return ResourceManager.GetString("DiscordPlugin_ChannelToggleOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Bot is On.
        /// </summary>
        public static string DiscordPlugin_ChannelToggleOnContent {
            get {
                return ResourceManager.GetString("DiscordPlugin_ChannelToggleOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Integration.
        /// </summary>
        public static string DiscordPlugin_DisplayName {
            get {
                return ResourceManager.GetString("DiscordPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Your Discord Username (example: You#1234).
        /// </summary>
        public static string DiscordPlugin_UsernameLabelContent {
            get {
                return ResourceManager.GetString("DiscordPlugin_UsernameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string DisplayPlugin_DisplayName {
            get {
                return ResourceManager.GetString("DisplayPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Modes.
        /// </summary>
        public static string DisplayPlugin_ModeLabelContent {
            get {
                return ResourceManager.GetString("DisplayPlugin_ModeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show in Taskbar.
        /// </summary>
        public static string DisplayPlugin_ShowInTaskbarOffContent {
            get {
                return ResourceManager.GetString("DisplayPlugin_ShowInTaskbarOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Taskbar.
        /// </summary>
        public static string DisplayPlugin_ShowInTaskbarOnContent {
            get {
                return ResourceManager.GetString("DisplayPlugin_ShowInTaskbarOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horoscope.
        /// </summary>
        public static string HoroscopePlugin_DisplayName {
            get {
                return ResourceManager.GetString("HoroscopePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Zodiac Sign.
        /// </summary>
        public static string HoroscopePlugin_SelectionLabelContent {
            get {
                return ResourceManager.GetString("HoroscopePlugin_SelectionLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a name for this file.
        /// </summary>
        public static string LauncherPlugin_AddFileMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string LauncherPlugin_AddFileTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a name for this folder.
        /// </summary>
        public static string LauncherPlugin_AddFolderMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        public static string LauncherPlugin_AddFolderTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the URL of the search engine. Use {0} for query replacement..
        /// </summary>
        public static string LauncherPlugin_AddSearchEngineAddressMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddSearchEngineAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Address.
        /// </summary>
        public static string LauncherPlugin_AddSearchEngineAddressTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddSearchEngineAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type a name for the search engine. Example &apos;Google&apos;.
        /// </summary>
        public static string LauncherPlugin_AddSearchEngineNameMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddSearchEngineNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Name.
        /// </summary>
        public static string LauncherPlugin_AddSearchEngineNameTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddSearchEngineNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the URL of the website..
        /// </summary>
        public static string LauncherPlugin_AddWebsiteAddressMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddWebsiteAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Address.
        /// </summary>
        public static string LauncherPlugin_AddWebsiteAddressTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddWebsiteAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type a name for the website. Example &apos;Google&apos;.
        /// </summary>
        public static string LauncherPlugin_AddWebsiteNameMessage {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddWebsiteNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Name.
        /// </summary>
        public static string LauncherPlugin_AddWebsiteNameTitle {
            get {
                return ResourceManager.GetString("LauncherPlugin_AddWebsiteNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files, Folders &amp; Websites.
        /// </summary>
        public static string LauncherPlugin_DisplayName {
            get {
                return ResourceManager.GetString("LauncherPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string LogPlugin_DisplayName {
            get {
                return ResourceManager.GetString("LogPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string LogPlugin_WindowTitle {
            get {
                return ResourceManager.GetString("LogPlugin_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Zoom.
        /// </summary>
        public static string MapPlugin_DefaultZoomLabelContent {
            get {
                return ResourceManager.GetString("MapPlugin_DefaultZoomLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string MapPlugin_DisplayName {
            get {
                return ResourceManager.GetString("MapPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Provider.
        /// </summary>
        public static string MapPlugin_MapProviderLabelContent {
            get {
                return ResourceManager.GetString("MapPlugin_MapProviderLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Zoom.
        /// </summary>
        public static string MapPlugin_MaximumZoomLabelContent {
            get {
                return ResourceManager.GetString("MapPlugin_MaximumZoomLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Zoom.
        /// </summary>
        public static string MapPlugin_MinimumZoomLabelContent {
            get {
                return ResourceManager.GetString("MapPlugin_MinimumZoomLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs &amp; Videos.
        /// </summary>
        public static string MediaPlugin_DisplayName {
            get {
                return ResourceManager.GetString("MediaPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing has started. You will be notified when indexing is over..
        /// </summary>
        public static string MediaPlugin_IndexingMessage {
            get {
                return ResourceManager.GetString("MediaPlugin_IndexingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Songs Directory (Indexed {0} Files).
        /// </summary>
        public static string MediaPlugin_MusicDirectoryLabelContentFormat {
            get {
                return ResourceManager.GetString("MediaPlugin_MusicDirectoryLabelContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing [{0}].
        /// </summary>
        public static string MediaPlugin_MusicPlayerTitleFormat {
            get {
                return ResourceManager.GetString("MediaPlugin_MusicPlayerTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Videos Directory (Indexed {0} Files).
        /// </summary>
        public static string MediaPlugin_VideoDirectoryLabelContentFormat {
            get {
                return ResourceManager.GetString("MediaPlugin_VideoDirectoryLabelContentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsPlugin_DisplayName {
            get {
                return ResourceManager.GetString("NewsPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your News Feed.
        /// </summary>
        public static string NewsPlugin_FeedSelectionLabelContent {
            get {
                return ResourceManager.GetString("NewsPlugin_FeedSelectionLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a process name.
        /// </summary>
        public static string ProcessMonitorPlugin_AddProcessMessage {
            get {
                return ResourceManager.GetString("ProcessMonitorPlugin_AddProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string ProcessMonitorPlugin_AddProcessTitle {
            get {
                return ResourceManager.GetString("ProcessMonitorPlugin_AddProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Monitor.
        /// </summary>
        public static string ProcessMonitorPlugin_DisplayName {
            get {
                return ResourceManager.GetString("ProcessMonitorPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise intelligent events based on user interaction.
        /// </summary>
        public static string ProcessMonitorPlugin_ServiceDescription {
            get {
                return ResourceManager.GetString("ProcessMonitorPlugin_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        public static string ReminderPlugin_DisplayName {
            get {
                return ResourceManager.GetString("ReminderPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Reminder Service.
        /// </summary>
        public static string ReminderPlugin_ReminderServiceDescription {
            get {
                return ResourceManager.GetString("ReminderPlugin_ReminderServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services &amp; Plugins.
        /// </summary>
        public static string ServicePlugin_DisplayName {
            get {
                return ResourceManager.GetString("ServicePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string ServicePlugin_PluginTabHeader {
            get {
                return ResourceManager.GetString("ServicePlugin_PluginTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicePlugin_ServiceTabHeader {
            get {
                return ResourceManager.GetString("ServicePlugin_ServiceTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your API Key for Omdb.
        /// </summary>
        public static string ShowInfoPlugin_ApiKeyLabelContent {
            get {
                return ResourceManager.GetString("ShowInfoPlugin_ApiKeyLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        public static string ShowInfoPlugin_DisplayName {
            get {
                return ResourceManager.GetString("ShowInfoPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phrase you wish to save as a voice command.
        /// </summary>
        public static string SpeechPlugin_AddChoiceDialogMessage {
            get {
                return ResourceManager.GetString("SpeechPlugin_AddChoiceDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command.
        /// </summary>
        public static string SpeechPlugin_AddChoiceDialogTitle {
            get {
                return ResourceManager.GetString("SpeechPlugin_AddChoiceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the command value here....
        /// </summary>
        public static string SpeechPlugin_AddChoiceTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("SpeechPlugin_AddChoiceTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Commands.
        /// </summary>
        public static string SpeechPlugin_ChoiceTabItemHeader {
            get {
                return ResourceManager.GetString("SpeechPlugin_ChoiceTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        public static string SpeechPlugin_DisplayName {
            get {
                return ResourceManager.GetString("SpeechPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition Engine.
        /// </summary>
        public static string SpeechPlugin_EngineLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_EngineLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engines.
        /// </summary>
        public static string SpeechPlugin_EnginesTabItemHeader {
            get {
                return ResourceManager.GetString("SpeechPlugin_EnginesTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the word or phrase for voice command.
        /// </summary>
        public static string SpeechPlugin_GetChoiceMessage {
            get {
                return ResourceManager.GetString("SpeechPlugin_GetChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Command.
        /// </summary>
        public static string SpeechPlugin_GetChoiceTitle {
            get {
                return ResourceManager.GetString("SpeechPlugin_GetChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRGS.
        /// </summary>
        public static string SpeechPlugin_GrammarTabItemHeader {
            get {
                return ResourceManager.GetString("SpeechPlugin_GrammarTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Volume.
        /// </summary>
        public static string SpeechPlugin_MasterVolumeLabel {
            get {
                return ResourceManager.GetString("SpeechPlugin_MasterVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Volume.
        /// </summary>
        public static string SpeechPlugin_MicrophoneVolumeLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_MicrophoneVolumeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Rank (Equal and Above).
        /// </summary>
        public static string SpeechPlugin_RankLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_RankLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New speech settings saved..
        /// </summary>
        public static string SpeechPlugin_SettingsSavedMessage {
            get {
                return ResourceManager.GetString("SpeechPlugin_SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Speech Confidence.
        /// </summary>
        public static string SpeechPlugin_SynthesisConfidenceLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_SynthesisConfidenceLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Synthesis Rate.
        /// </summary>
        public static string SpeechPlugin_SynthesisRateLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_SynthesisRateLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Synthesis Engine.
        /// </summary>
        public static string SpeechPlugin_SynthesizerLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_SynthesizerLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesizer Voice.
        /// </summary>
        public static string SpeechPlugin_VoiceLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_VoiceLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Synthesis Volume.
        /// </summary>
        public static string SpeechPlugin_VolumeLabelContent {
            get {
                return ResourceManager.GetString("SpeechPlugin_VolumeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Thread Culture.
        /// </summary>
        public static string SystemPlugin_CultureLabelContent {
            get {
                return ResourceManager.GetString("SystemPlugin_CultureLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemPlugin_DisplayName {
            get {
                return ResourceManager.GetString("SystemPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset and Shutdown.
        /// </summary>
        public static string SystemPlugin_ResetButtonContent {
            get {
                return ResourceManager.GetString("SystemPlugin_ResetButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Dashboard.
        /// </summary>
        public static string SystemPlugin_RestartButtonContent {
            get {
                return ResourceManager.GetString("SystemPlugin_RestartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application UI Culture.
        /// </summary>
        public static string SystemPlugin_UserInterfaceCultureLabelContent {
            get {
                return ResourceManager.GetString("SystemPlugin_UserInterfaceCultureLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Working Directory.
        /// </summary>
        public static string SystemPlugin_WorkingDirectoryButtonContent {
            get {
                return ResourceManager.GetString("SystemPlugin_WorkingDirectoryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Telegram Bot Token.
        /// </summary>
        public static string TelegramPlugin_BotTokenLabelContent {
            get {
                return ResourceManager.GetString("TelegramPlugin_BotTokenLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Bot is Off.
        /// </summary>
        public static string TelegramPlugin_ChannelToggleOffContent {
            get {
                return ResourceManager.GetString("TelegramPlugin_ChannelToggleOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Bot is On.
        /// </summary>
        public static string TelegramPlugin_ChannelToggleOnContent {
            get {
                return ResourceManager.GetString("TelegramPlugin_ChannelToggleOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Integration.
        /// </summary>
        public static string TelegramPlugin_DisplayName {
            get {
                return ResourceManager.GetString("TelegramPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Your Telegram Username.
        /// </summary>
        public static string TelegramPlugin_UsernameLabelContent {
            get {
                return ResourceManager.GetString("TelegramPlugin_UsernameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes &amp; Colors.
        /// </summary>
        public static string ThemePlugin_DisplayName {
            get {
                return ResourceManager.GetString("ThemePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic Tac Toe.
        /// </summary>
        public static string TicTacToePlugin_DisplayName {
            get {
                return ResourceManager.GetString("TicTacToePlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Difficulty.
        /// </summary>
        public static string TicTacToePlugin_PlayerDifficultyContent {
            get {
                return ResourceManager.GetString("TicTacToePlugin_PlayerDifficultyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Player.
        /// </summary>
        public static string TicTacToePlugin_PlayerLabelContent {
            get {
                return ResourceManager.GetString("TicTacToePlugin_PlayerLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserPlugin_DisplayName {
            get {
                return ResourceManager.GetString("UserPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (The Bot will call you by this name).
        /// </summary>
        public static string UserPlugin_NameLabelContent {
            get {
                return ResourceManager.GetString("UserPlugin_NameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string WeatherPlugin_DisplayName {
            get {
                return ResourceManager.GetString("WeatherPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Your Location (example: Washington).
        /// </summary>
        public static string WeatherPlugin_LocationLabelContent {
            get {
                return ResourceManager.GetString("WeatherPlugin_LocationLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Temperature Unit.
        /// </summary>
        public static string WeatherPlugin_TemperatureUnitLabelContent {
            get {
                return ResourceManager.GetString("WeatherPlugin_TemperatureUnitLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia.
        /// </summary>
        public static string WikipediaPlugin_DisplayName {
            get {
                return ResourceManager.GetString("WikipediaPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string WindowsPlugin_DisplayName {
            get {
                return ResourceManager.GetString("WindowsPlugin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Directory.
        /// </summary>
        public static string WindowsPlugin_ScreenshotLabelContent {
            get {
                return ResourceManager.GetString("WindowsPlugin_ScreenshotLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Directory.
        /// </summary>
        public static string WindowsPlugin_WallpaperLabelContent {
            get {
                return ResourceManager.GetString("WindowsPlugin_WallpaperLabelContent", resourceCulture);
            }
        }
    }
}
